#!/bin/sh
#===============================================================================
#
#  Copyright (C) 2021 by Digi International Inc.
#  All rights reserved.
#
#  This program is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License version 2 as published by
#  the Free Software Foundation.
#
#
#  !Description: Verifies successful boot
#
#===============================================================================

dualboot_init () {
	ACTIVE_SYSTEM="$(fw_printenv -n active_system 2>/dev/null)"
        ACTIVE_SYSTEM_SET="$(echo $?)"
        if [ "$ACTIVE_SYSTEM_SET" = "1" ]; then
                PARTTABLE="/proc/mtd"
                MTDINDEX="$(sed -ne "s/\(^mtd[0-9]\+\):.*\<environment\>.*/\1/g;T;p" ${PARTTABLE} 2>/dev/null)"

                if [ -z "${MTDINDEX}" ]; then
                        BOOT_PART="$(fw_printenv -n mmcpart 2>/dev/null)"
                        BOOT_DEV="$(fw_printenv -n mmcbootdev 2>/dev/null)"

                        CURRENT_PART="$(ls -l /dev/disk/by-partlabel/ | grep -i mmcblk${BOOT_DEV}p${BOOT_PART} | awk '{print $9}')"
                        fw_setenv active_system "${CURRENT_PART}"
                else
                        MTD_BOOT_PART="$(fw_printenv -n mtdbootpart 2>/dev/null)"
                        fw_setenv active_system "${MTD_BOOT_PART}"
                fi
        fi

	ISUPGRADING=$(fw_printenv upgrade_available | awk -F'=' '{print $2}')

	if [ "$ISUPGRADING" = "1" ]
	then
		BOOTCOUNT="$(fw_printenv -n bootcount 2>/dev/null)"
		if [ "${BOOTCOUNT}" -lt 3 ]; then
			fw_setenv upgrade_available
			fw_setenv bootcount 0
		fi
	fi
}

case "$1" in
	start)
		echo -n "Starting dualboot check: "
		dualboot_init
		echo "done."
		;;
	stop)
		;;
	restart)
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
